"""Build the MATS write-up (Google-Doc-ready) from committed artifacts: one content model, two renderers (.docx and .html).

Structure follows Neel Nanda's MATS 12.0 application doc: exec summary (<=600 words, graphs, one paragraph
and graph per key experiment), randomly selected examples immediately after, a "what I verified" section,
narrative order (not chronological), prompts and metric definitions, limitations, process last.
The executive summary text lives in results/writeup/doc/exec_summary_final.md (the applicant rewrites it).
"""
import base64, html, os, re, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
from src.controlled_focal_agent import SPONTANEOUS_SYSTEM_TEMPLATE, ELICITED_SYSTEM_TEMPLATE, SPONTANEOUS_SYSTEM_TEMPLATE_PARAPHRASE_1  # noqa: E402
W = os.path.join(ROOT, "results", "writeup"); D = os.path.join(W, "doc"); os.makedirs(D, exist_ok=True)
mat = open(os.path.join(W, "WRITEUP_MATERIALS.md"), encoding="utf-8").read()
summary = open(os.path.join(D, "exec_summary_final.md"), encoding="utf-8").read().strip()

def section(title):
    m = re.search(r"^## %s.*?$" % re.escape(title), mat, flags=re.M)
    if not m: return ""
    start = m.end(); nxt = re.search(r"^## ", mat[start:], flags=re.M); return mat[start:start + nxt.start()] if nxt else mat[start:]

def num(label):
    m = re.search(r"^\| %s \| (.+?) \| `" % re.escape(label), mat, flags=re.M); return m.group(1) if m else "[MISSING: %s]" % label

# ---------------------------------------------------------------- content model
C = []
def h1(t): C.append(("h1", t))
def h2(t): C.append(("h2", t))
def h3(t): C.append(("h3", t))
def p(t): C.append(("p", t))
def bullets(items): C.append(("bullets", items))
def fig(name, cap): C.append(("fig", name, cap))
def md(text): C.append(("md", text))
def code(text): C.append(("code", text))

h1("LatentTarget: does an LLM learn which persuasion frame a hidden partner responds to, and does it hold a model of that partner?")
p("Aayush (Rishi) Ghosh · MATS 12.0 application, Neel Nanda stream · code and logs: github.com/4r4cn1d0/LatentTarget · [CONFIRM: hours on the project task, e.g. 'about 20 hours over Aug 26 to Sep 4; write-up 2 hours'; attach the Toggl screenshot if you have one]")
p("Every number in this document is generated from committed artifacts by scripts/make_writeup_materials.py and names its source file in Appendix A. Figures are generated by the same script from the raw logs.")

h1("Executive summary")
for para in summary.split("\n\n"):
    para = para.strip()
    if not para: continue
    if para.startswith("[FIG:"):
        name, cap = para[5:].split("]", 1); fig(name.strip(), cap.strip())
    elif para.startswith("- "):
        bullets([l[2:] for l in para.split("\n") if l.startswith("- ")])
    else:
        p(para)

h1("Randomly selected examples (seeded draws, not chosen)")
p("Nanda's doc asks for random examples right after the summary, so here they are. Each is a line drawn uniformly at random from the raw log of that run using the seed shown. The model sees the three candidates without labels; the frame labels are the registered ground truth; the arrow marks the model's choice; the target's realized P(A) and choice follow. For the elicited arm the raw JSON output is shown.")
h3("V4, Qwen3.8-27B, spontaneous prompt (seed 0, five draws from 7,200 records)"); md(section("Randomly selected V4 examples"))
h3("Arm P1, Qwen3.8-27B, reworded prompt (seed 3, three draws from 7,200)"); md(section("Randomly selected examples — Arm P1"))
h3("Arm R1, Gemma-4-31B (seed 1, three draws from 7,200)"); md(section("Randomly selected examples — Arm R1"))
h3("Arm E1, Qwen3.8-27B, elicited beliefs (seed 2, three draws from 3,600)"); md(section("Randomly selected examples — Arm E1"))

h1("What I verified myself, and how")
p("Nearly all code in this repository was written by an AI coding agent (Claude in Claude Code; earlier sessions in OpenAI Codex). The list below is what I checked and what I did not. [CONFIRM every item: delete any you did not personally do.]")
bullets([
    "Preregistration: every real run has a frozen spec (thresholds, seeds, bank hash) committed before data existed, and each arm was analysed once with the frozen analyzer. A failed gate stops the arm; nothing was re-tuned after a result. Commits and dates are in docs/WORK_LOG.md.",
    "Pipeline can detect learning: a mock Bayesian learner run through the identical pipeline passes the same gates (`MOCK_PIPELINE_PASS_NOT_SCIENTIFIC_EVIDENCE`), and a mock non-learner fails them. So a flat result is not a broken analyzer.",
    "Read raw transcripts: [CONFIRM: how many transcripts you read, from which runs, and what you looked for, e.g. 'I read 20 full episodes from V4 (10 full-history, 10 swap) and 10 from E1 and confirmed the candidate messages carried the registered frames and the target responses matched the logged P(A)'].",
    "Belief equals choice is real, not a parser artefact: the runner records the model's own JSON `choice` field; in 3,600 of 3,600 elicited records that stated choice was in the argmax set of the model's own stated probabilities (25 ties, all resolved by the model's `choice`). I re-derived this with a fresh script over the raw log.",
    "No position bias: chosen slot shares are 0.34/0.33/0.33 (Gemma) and 0.31/0.35/0.35 (elicited Qwen); the candidate order is shuffled per round by seed.",
    "History sensitivity, model-free: P(repeat frame | success) minus P(repeat | failure) is 0.183 for Qwen V4 and 0.031 for Gemma; Gemma's choice equals its shuffled-history choice on the identical candidate triple 90.5% of the time (Qwen 63.7%). Computed directly from the logs, independent of the analyzer.",
    "Numbers in this document are generated, not typed: scripts/make_writeup_materials.py reads the committed result files and emits every figure and the numbers sheet in Appendix A with a source per row.",
    "Message bank frames: two blind machine judges labelled the bank; a 45-template blind hand-label sheet exists. [CONFIRM: 'I labelled it and agreement with the registered frames was X/45' or 'I have not scored it yet'.]",
    "Adversarial review of my own rule: the V7 revision rule was rejected because a five-lens review showed its pooled test would pass on pure default attraction with no updating. docs/V7_REVIEW.md.",
    "Tests: 793 pass, including tests that pin the V4 prompt text by hash, the registered thresholds, and the on-disk Gemma prior measurement against its raw log.",
    "What I did not check line by line: [CONFIRM: e.g. 'the analyzer's bootstrap and sign-flip implementations; I checked their outputs against a hand computation for one condition' or 'none of the analyzer code'].",
])

h1("1. The question, and why I chose it")
p("Persuasion is the case where a model's picture of the person it is talking to matters most. Chen et al. show that LLMs form accurate models of static user attributes from little text. I wanted the dynamic version: over a repeated interaction with feedback, does the model learn which kind of argument this particular partner responds to, does it revise that when the partner silently changes, and is there any stated belief about the partner that is separate from the choice it makes? A persuader that holds and updates such a model is a different safety object from one with a fixed style, and any interpretability claim about a target representation needs the behavioural effect first.")
p("Hypotheses, written before the V4 run: H1, with its own history the model matches the partner's frame more often than chance; H2, the effect depends on its own history, not on any history (shuffled-history control) and not on a partner that ignores it (random-target control); H3, it generalises to unseen wording of the same frames; H4, after a silent change of partner it moves to the new frame and away from the old one. A further question, tested later: is a stated belief separable from the choice?")
p("Why a controlled choice rather than free-form persuasion: in a free-form design 'which frame did the model use' is a judge's opinion, and judge noise swamps a modest learning effect. Here the model picks one of three registered messages, one per frame, and the partner responds to the registered frame. Learning becomes a match rate with no judge in the loop. The price is that the model does not write the persuasion; it selects it.")

h1("2. Setup")
h2("2.1 Environment and conditions")
bullets([
    "Round: a scenario with Option A and Option B, three unlabelled candidate messages (one per frame: fairness, risk, expertise) from a registered bank of 90 templates with 45 held-out paraphrases, presented in seeded random order. The model answers 1, 2, or 3.",
    "Partner: a simulator with a hidden type. P(chooses A) = 0.72 if the candidate's registered frame matches its type, 0.38 otherwise. Same bank, seeds, and targets in every arm.",
    "Episode: 20 rounds. Rounds 16 to 20 use held-out wording. In swap episodes the type changes silently after round 10.",
    "Conditions: full history (own transcript so far), no history, shuffled history (another episode's transcript), random target (partner ignores the frame), swap. 60 episodes per stable condition, 120 swap episodes: 360 episodes and 7,200 choices per full run.",
    "Models: Qwen/Qwen3.8-27B and google/gemma-4-31B-it, open weights, pinned revisions, bf16 on one A100-80GB, greedy decoding, single-digit answers (max 8 tokens; 96 for the elicited JSON).",
])
h2("2.2 Metrics")
bullets([
    "Match: the chosen candidate's registered frame equals the partner's current type.",
    "Learning gain: mean match on held-out rounds 16 to 20 minus mean match on rounds 1 to 5, per episode; reported with episode-bootstrap 95% CIs.",
    "Difference-in-differences: full-history gain minus no-history gain, with a one-sided sign-flip randomization test over episodes (10,000 draws).",
    "Revision: for swap episodes, new-frame gain (late new-frame use minus pre-swap new-frame use), old-frame drop, and late new-over-old, with the same test. The registered revision gate requires a positive new-over-old at α = 0.05.",
    "Model-free diagnostics (not gates): win-stay/lose-shift, P(repeat frame | success) minus P(repeat | failure); and same-choice agreement between conditions on the identical candidate triple.",
])
h2("2.3 Prompts, verbatim")
p("V4 spontaneous system prompt (the frozen text; pinned by SHA-256 in tests/test_prompt_variant.py):"); code(SPONTANEOUS_SYSTEM_TEMPLATE.format(n_rounds=20))
p("Arm P1 reworded system prompt (same facts, different sentences):"); code(SPONTANEOUS_SYSTEM_TEMPLATE_PARAPHRASE_1.format(n_rounds=20))
p("Arm E1 elicited system prompt (the model must state a probability per candidate, and its past predictions are shown in its history):"); code(ELICITED_SYSTEM_TEMPLATE.format(n_rounds=20))
p("The user turn shows the scenario, the visible history (previous rounds' three candidates, the model's choice, and the partner's choice), and the three current candidates. Prohibited phrasing (for example 'hidden type', 'susceptibility', 'adapt to the participant') is checked by the audit; the prompts never name the frames.")

h1("3. Experiment 1: does the model learn the partner's frame? (V4, Qwen3.8-27B)")
p("Prediction before the run: H1 to H3 hold if full-history learning gain > 0 with the three controls flat, and the effect survives on held-out wording. Possible outcomes: no learning (everything flat), learning that is really a default frame (full and no-history both high on one frame), or genuine feedback-driven learning.")
p("Outcome: with its own history the held-out match rate rose from %s early to %s late; no-history stayed at 0.333, shuffled history fell from 0.287 to 0.233, random target was flat. Learning gain %s; the registered randomization test passed. Learning is anti-default: expertise is the model's default frame (0.922 of no-history picks), so the gains come on fairness targets (0.24 vs 0.05) and risk targets (0.61 vs 0.10), while expertise targets show nothing to learn (0.86 vs 0.85)." % (num("V4 full_history early match"), num("V4 full_history late held-out match"), num("V4 full_history learning gain (late held-out − early), 95% CI")))
fig("fig_w1_v4_learning_by_condition.png", "Figure 2. V4, Qwen3.8-27B: P(chosen frame matches the hidden target) by round, four stable conditions. Grey band: held-out wording.")
fig("fig_w6_v4_learning_by_target.png", "Figure 3. V4 per hidden target: full history vs no history vs shuffled. Learning is largest where the default frame is weakest.")

h1("4. Experiment 2: does it revise after a silent change of partner? (V4 swap)")
p("Prediction: H4 holds if, after the swap at round 10, new-frame use rises and old-frame use falls, with late new-over-old positive at α = 0.05. The alternative I worried about: adaptation that only ever runs toward the default frame.")
p("Outcome: the registered test failed. New-frame gain and old-frame drop were symmetric (%s), and the pattern by transition is the alternative: 34 of 40 swaps into expertise 'adapted', 0 of 40 into fairness. That is the default frame re-asserting itself, not an update to a model of the partner." % num("V4 swap into expertise (default): new gain / old drop / adapted"))
fig("fig_w2_v4_swap_by_transition.png", "Figure 4. V4 silent swap: new-frame gain and old-frame drop per ordered transition, with the number of episodes that reached three of four new-frame picks after the swap.")

h1("5. Experiment 3: three stress tests, each declared before its outcome")
p("After V4 I wrote docs/V4_REPLICATION_DECLARATION.md with predictions for three arms, then ran each once with the frozen design and analyzer. Figure 1 shows all four with-history curves side by side.")
h2("5.1 Arm P1: does the effect survive rewording the prompt? Yes.")
p("Prediction: if the effect is a property of the model under this design, P1 replicates; if it depends on the exact prompt string, the gain is near zero. Outcome: gain %s (V4: 0.187); full minus no-history difference-in-differences %s; controls flat; per-target advantage fairness 0.28, risk 0.43, expertise 0.09. Revision failed as predicted. The frozen decision is still STOP because the valid-selection gate failed at %s: under the new wording the model began a reasoning preamble ('Looking at the history, the participant chose…') in about 10%% of history rounds and 0%% of no-history rounds, and was cut off by the token budget. The fallback is a uniform random pick, which can only pull learning toward chance: parsed-only late match %s. I did not re-run with a larger budget, because the arm was declared with V4 decoding unchanged." % (num("P1 paraphrase full_history learning gain (late held-out − early), 95% CI"), num("P1 paraphrase full − no-history difference-in-differences, one-sided p"), num("P1 paraphrase valid selection rate (gate 0.98)"), num("P1 full_history late held-out match: all rounds / parsed-only")))
h2("5.2 Arm R1: does it replicate on a second model family? No.")
p("Prediction: H1 to H3 replicate on Gemma-4-31B-it with the same default-attraction failure of revision. Outcome: gain %s; every effect gate but the random-target control failed. Gemma is nearly insensitive to both history and feedback: its choice equals its shuffled-history choice on the identical triple %s of the time, and P(repeat frame) is %s. Its no-history default is weaker than Qwen's (0.787 vs 0.922 expertise), so default strength does not explain the difference; feedback use does. Per-target movement is toward the default (expertise 1.00 vs 0.72 no-history; fairness 0.01 vs 0.16), the opposite of Qwen." % (num("R1 Gemma full_history learning gain (late held-out − early), 95% CI"), num("Gemma R1 same choice as full_history: shuffled_history").split(" ")[0], num("Gemma R1 full_history: P(repeat frame | success) / P(repeat | failure) / gap")))
fig("fig_w10_history_sensitivity_qwen_vs_gemma.png", "Figure 5. Model-free diagnostics. Left: P(repeat last round's frame) after a success vs after a failure. Right: same choice as full history on the identical candidate triple, against shuffled history, no history, and a random target.")
h2("5.3 Arm E1: is there a stated belief separate from the choice? No, and the effect disappears.")
p("Prediction: if a belief exists that the behaviour ignores, P(stated belief = new frame) rises after the swap while P(choice = new frame) does not; if they move together, the stated belief is a description of the policy. Outcome: neither moved. Under the elicited prompt the same Qwen showed no learning (gain %s; elicited minus spontaneous %s), picked expertise 94.2%% of rounds and fairness never, and its choice was the argmax of its own stated probabilities in 3,600 of 3,600 records. Stated confidence is a fixed frame ranking (expertise 0.69 > risk 0.58 > fairness 0.49) that moves by about 0.05 with feedback without ever changing the choice; post-swap P(belief = new) minus P(choice = new) = %s. Caveat: E1 changed two things at once, the output format and the model seeing its own past predictions; it cannot separate them." % (num("E1 elicited elicited_full_history learning gain (late held-out − early), 95% CI"), num("E1 − V4 spontaneous: full-history learning gain diff, 95%% CI").replace("[MISSING", "[MISSING"), num("E1 elicited_swap post-swap rounds 1-5: P(belief=new) − P(choice=new), 95% CI")))
fig("fig_w9_elicited_belief_vs_choice.png", "Figure 6. Arm E1: stated belief and choice by round (left, middle) and after the silent swap by rounds since swap (right). The two lines coincide.")

h1("6. What the evidence supports, and the strongest case against")
bullets([
    "Supported: a real, preregistered, wording-robust behavioural effect on one model. Qwen3.8-27B, given only outcomes, moves its choice toward the frame that works, on unseen wording, and the three controls rule out history length, any-history, and a partner that ignores it.",
    "Not supported: a latent model of the partner. Revision fails through default attraction; forcing the model to state beliefs removes the effect and shows belief and choice are one object; a second model family shows nothing.",
    "Strongest alternative explanation: a model-free policy, 'repeat what worked, otherwise fall back to expertise', plus a strong default. It fits every result. What would separate it from a partner model: revision away from the default, or a stated belief that leads the choice. Neither happened.",
    "What I did not do and why: no activation capture, probe, or steering. The plan gated them behind a passed revision test, which never came, and the E1 result made a probe for 'the partner's type' moot until a behavioural effect survives model and format changes.",
])

h1("7. Limitations, and whether I could have addressed them")
bullets([
    "One positive model out of two. A third model under the spontaneous prompt would separate 'Qwen' from 'feedback-sensitive'. Cost about $3; not run.",
    "The partner is a simulator with a fixed rule, not a human or an LLM with a persona. An LLM target would be more realistic at the cost of judge noise on 'did it respond to the frame'.",
    "The persuasion is a choice among pre-written messages, not generated text. This was the price of a judge-free metric.",
    "The expertise default confounds revision. Four redesigns to remove it stopped at their own preregistered gates (section 8). A two-frame design with a distractor is the fix I would try next.",
    "E1 cannot separate the format change from the model seeing its own predictions. A third arm with predictions hidden from the history would fix that for about $3; not run.",
    "P1's validity gate failed on truncated reasoning preambles. A larger token budget would remove it; not re-run because the arm was declared with V4 decoding.",
    "Message-bank frames were labelled by two blind machine judges; the 45-template hand-label sheet is [CONFIRM: scored / not yet scored].",
    "N = 60 episodes per stable condition limits power for smaller effects; the swap analysis has 20 episodes per transition.",
])

h1("8. Process: what I stopped, and why (in brief)")
p("Four successors to V4 were designed to remove the default-frame confound. Each had a feasibility rule written down before any spend, and each stopped at it. V5: the calibrated bank could not be balanced (no-history shares 13.7/34.2/52.1 against a 25 to 42% rule). V6: the balance gate was infeasible at every allowed N in a 120,000-study screen. V7: failed its own feasibility rule, and an adversarial review showed its pooled revision rule would pass on pure default attraction. V8: controlled Type I error (0 joint rejections in 6,000 null studies) but was underpowered against the weakest registered learner. I also dropped a planned first-crossing 'probe leads behaviour' metric after simulating it: a chance-level probe appears to lead by 0.91 rounds with a CI excluding zero in 87% of runs (Figure 8).")
md(section("Gate ledger"))
fig("fig_w3_default_frame_priors.png", "Figure 7. No-history frame shares: the expertise default across banks and models.")
fig("fig_w5_first_crossing_bias.png", "Figure 8. Why the first-crossing lag metric was dropped: apparent probe lead from noise alone.")

h1("9. How I used LLMs")
p("[CONFIRM and rewrite in your words.] Nearly all code, analysis scripts, and documentation were written by Claude in Claude Code, with earlier sessions in OpenAI Codex. GPT-5.6 served as two blind judges labelling the message bank's frames. I set the question, chose the controlled-choice design over free-form persuasion, decided at every gate whether to stop or continue, and declared the three stress tests. The checks I relied on are listed in 'What I verified myself'. A major error in the primary V4 result would surprise me a lot: the controls, the mock-learner validation, the independent replication under a reworded prompt, and the seeded examples all point the same way. An error in a secondary diagnostic would surprise me less. The frame labels of the bank are the part I trust least until the hand-labelling is scored.")

h1("Appendix A. Sourced numbers")
md(section("Numbers sheet"))
h1("Appendix B. Reproduction")
p("Specs: docs/behavioral_checkpoint_v4.json, docs/v4_paraphrase_qwen38.json, docs/v4_replication_gemma4.json, docs/v4_elicited_qwen38.json. Declarations and outcomes: docs/V4_REPLICATION_DECLARATION.md. Runner: scripts/run_controlled_open_weight.py (pod bootstraps in scripts/pod_bootstrap_*.sh). Analyzers: scripts/analyze_controlled_v4.py, scripts/analyze_elicited_choices.py, scripts/analyze_elicited_beliefs.py. Materials and figures: scripts/make_writeup_materials.py. Log of every decision: docs/WORK_LOG.md. Tests: 793.")

# ---------------------------------------------------------------- renderers
def esc(s): return html.escape(s)
def inline_html(s):
    s = esc(s); s = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", s); s = re.sub(r"`([^`]+)`", r"<code>\1</code>", s); return s
def md_html(text):
    out = []; lines = text.split("\n"); i = 0
    while i < len(lines):
        l = lines[i]
        if l.startswith("|"):
            rows = []
            while i < len(lines) and lines[i].startswith("|"): rows.append(lines[i]); i += 1
            cells = [[c.strip() for c in r.strip().strip("|").split("|")] for r in rows if not re.match(r"^\|[-| ]+\|$", r.strip())]
            out.append("<table border='1' cellpadding='4' style='border-collapse:collapse;font-size:85%'>" + "".join("<tr>" + "".join(("<th>" if k == 0 else "<td>") + inline_html(c) + ("</th>" if k == 0 else "</td>") for c in row) + "</tr>" for k, row in enumerate(cells)) + "</table>"); continue
        if l.startswith("- "): out.append("<p style='margin-left:1.2em'>• " + inline_html(l[2:]) + "</p>")
        elif l.startswith("## "): out.append("<h3>" + inline_html(l[3:]) + "</h3>")
        elif l.strip() and not l.startswith("# "): out.append("<p>" + inline_html(l) + "</p>")
        i += 1
    return "\n".join(out)
def render_html():
    parts = []
    for item in C:
        k = item[0]
        if k == "h1": parts.append("<h1>%s</h1>" % esc(item[1]))
        elif k == "h2": parts.append("<h2>%s</h2>" % esc(item[1]))
        elif k == "h3": parts.append("<h3>%s</h3>" % esc(item[1]))
        elif k == "p": parts.append("<p>%s</p>" % inline_html(item[1]))
        elif k == "bullets": parts.append("<ul>" + "".join("<li>%s</li>" % inline_html(b) for b in item[1]) + "</ul>")
        elif k == "code": parts.append("<pre style='background:#f4f4f4;padding:8px;white-space:pre-wrap;font-size:85%%'>%s</pre>" % esc(item[1]))
        elif k == "md": parts.append(md_html(item[1]))
        elif k == "fig":
            pth = os.path.join(W, item[1])
            if os.path.exists(pth):
                b = base64.b64encode(open(pth, "rb").read()).decode(); parts.append('<p><img src="data:image/png;base64,%s" style="max-width:100%%"/></p><p><i>%s</i></p>' % (b, esc(item[2])))
    open(os.path.join(D, "MATS_WRITEUP.html"), "w", encoding="utf-8").write("<html><head><meta charset='utf-8'><title>LatentTarget MATS write-up</title></head><body style='font-family:Arial,sans-serif;max-width:900px;margin:auto;line-height:1.4'>" + "\n".join(parts) + "</body></html>")

def render_docx():
    from docx import Document
    from docx.shared import Inches, Pt
    doc = Document(); st = doc.styles["Normal"]; st.font.name = "Arial"; st.font.size = Pt(11)
    def runs(par, text):
        for tok in re.split(r"(\*\*.+?\*\*|`[^`]+`)", text):
            if not tok: continue
            if tok.startswith("**"): r = par.add_run(tok[2:-2]); r.bold = True
            elif tok.startswith("`"): r = par.add_run(tok[1:-1]); r.font.name = "Courier New"
            else: par.add_run(tok)
    def md_docx(text):
        lines = text.split("\n"); i = 0
        while i < len(lines):
            l = lines[i]
            if l.startswith("|"):
                rows = []
                while i < len(lines) and lines[i].startswith("|"): rows.append(lines[i]); i += 1
                cells = [[c.strip() for c in r.strip().strip("|").split("|")] for r in rows if not re.match(r"^\|[-| ]+\|$", r.strip())]
                if cells:
                    ncol = len(cells[0]); t = doc.add_table(rows=len(cells), cols=ncol); t.style = "Table Grid"
                    for a, row in enumerate(cells):
                        for b in range(ncol):
                            c = row[b] if b < len(row) else ""; cell = t.cell(a, b); cell.text = ""; runs(cell.paragraphs[0], c)
                            for r in cell.paragraphs[0].runs: r.font.size = Pt(8); r.bold = bool(r.bold) or a == 0
                    doc.add_paragraph()
                continue
            if l.startswith("- "): runs(doc.add_paragraph(style="List Bullet"), l[2:])
            elif l.startswith("## "): doc.add_heading(l[3:], level=3)
            elif l.strip() and not l.startswith("# "): runs(doc.add_paragraph(), l)
            i += 1
    for item in C:
        k = item[0]
        if k == "h1": doc.add_heading(item[1], level=1)
        elif k == "h2": doc.add_heading(item[1], level=2)
        elif k == "h3": doc.add_heading(item[1], level=3)
        elif k == "p": runs(doc.add_paragraph(), item[1])
        elif k == "bullets":
            for b in item[1]: runs(doc.add_paragraph(style="List Bullet"), b)
        elif k == "code":
            par = doc.add_paragraph(); r = par.add_run(item[1]); r.font.name = "Courier New"; r.font.size = Pt(9)
        elif k == "md": md_docx(item[1])
        elif k == "fig":
            pth = os.path.join(W, item[1])
            if os.path.exists(pth):
                doc.add_picture(pth, width=Inches(6.3)); c = doc.add_paragraph(); r = c.add_run(item[2]); r.italic = True; r.font.size = Pt(9)
    doc.save(os.path.join(D, "MATS_WRITEUP.docx"))

def render_txt():
    out = []
    for item in C:
        k = item[0]
        if k in ("h1", "h2", "h3"): out.append("\n" + ("#" * int(k[1])) + " " + item[1] + "\n")
        elif k == "p": out.append(item[1] + "\n")
        elif k == "bullets": out.extend("- " + x for x in item[1]); out.append("")
        elif k == "code": out.append("```\n" + item[1] + "\n```\n")
        elif k == "md": out.append(item[1])
        elif k == "fig": out.append("[Figure: %s] %s\n" % (item[1], item[2]))
    open(os.path.join(D, "MATS_WRITEUP.txt"), "w", encoding="utf-8").write("\n".join(out))

render_html(); render_docx(); render_txt()
words = len(re.findall(r"\S+", re.sub(r"\[CONFIRM[^\]]*\]", "", "\n".join(l for l in summary.split("\n") if not l.startswith("[FIG:")))))
missing = re.findall(r"\[MISSING: [^\]]+\]", open(os.path.join(D, "MATS_WRITEUP.html")).read())
print("wrote MATS_WRITEUP.docx and .html | exec summary words: %d | missing number labels: %s" % (words, missing or "none"))
